"""empty message

Revision ID: 165240de4bd7
Revises: 4c14be695189
Create Date: 2019-12-19 23:00:49.868000

"""

# revision identifiers, used by Alembic.
revision = '165240de4bd7'
down_revision = '4c14be695189'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('in_out', 'changenumber',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('in_out', 'inorout',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('in_out', 'inorout',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('in_out', 'changenumber',
               existing_type=sa.FLOAT(),
               nullable=False)
    ### end Alembic commands ###
