"""empty message

Revision ID: 4c14be695189
Revises: None
Create Date: 2019-12-19 22:59:09.591000

"""

# revision identifiers, used by Alembic.
revision = '4c14be695189'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
